name: Auto update seminars (remove widgets and update static links)

on:
  push:
    branches:
      - main
    paths:
      - seminars/**

jobs:
  rm-widgets:
    name: 'Build handbook'
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install jq and moreutils
        run: |
          sudo apt-get update
          sudo apt-get install -y jq moreutils

      - name: Remove widgets from seminars
        run: bash ./seminars/rm_widgets.sh

      - name: Update static links in seminars
        run: python3 ./seminars/update_static_links.py

      - name: Configure Git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Commit changes
        run: git add ./seminars && git commit -m "Update seminar notebooks" || exit 0

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

